dataTable1 = {
    "Contacts per index case": {
        "ControlArm": 3.4,
        "ControlArmPercent": None,
        "InterArm": 4.0,
        "InterArmPercent": None,
        "Total": 3.7,
    },
    "Age group": {
        "≤5 years": {
            "ControlArm": 534,
            "ControlArmPercent": 11.3,
            "InterArm": 625,
            "InterArmPercent": 11.1,
            "Total": 1159,
            "TotalPercent": 11.2,
        },
        "6_17 years": {
            "ControlArm": 1448,
            "ControlArmPercent": 30.7,
            "InterArm": 1665,
            "InterArmPercent": 29.6,
            "Total": 3113,
            "TotalPercent": 30.1,
        },
        "18_59 years": {
            "ControlArm": 2513,
            "ControlArmPercent": 53.2,
            "InterArm": 3001,
            "InterArmPercent": 53.4,
            "Total": 5514,
            "TotalPercent": 53.3,
        },
        "≥60 years": {
            "ControlArm": 229,
            "ControlArmPercent": 4.8,
            "InterArm": 330,
            "InterArmPercent": 5.9,
            "Total": 559,
            "TotalPercent": 5.4,
        },
    },
    "Sex": {
        "Male": {
            "ControlArm": 2121,
            "ControlArmPercent": 44.9,
            "InterArm": 2583,
            "InterArmPercent": 46.0,
            "Total": 4704,
            "TotalPercent": 45.5,
        },
        "Female": {
            "ControlArm": 2603,
            "ControlArmPercent": 55.1,
            "InterArm": 3038,
            "InterArmPercent": 54.0,
            "Total": 5641,
            "TotalPercent": 54.5,
        },
    },
    "Marital status": {
        "Single": {
            "ControlArm": 2628,
            "ControlArmPercent": 55.6,
            "InterArm": 3102,
            "InterArmPercent": 55.2,
            "Total": 5730,
            "TotalPercent": 55.4,
        },
        "Married": {
            "ControlArm": 1845,
            "ControlArmPercent": 39.1,
            "InterArm": 2271,
            "InterArmPercent": 40.4,
            "Total": 4116,
            "TotalPercent": 39.8,
        },
        "Separated or widowed": {
            "ControlArm": 251,
            "ControlArmPercent": 5.3,
            "InterArm": 248,
            "InterArmPercent": 4.4,
            "Total": 499,
            "TotalPercent": 4.8,
        },
    },
    "Caste*": {
        "Scheduled tribes": {
            "ControlArm": 3132,
            "ControlArmPercent": 66.3,
            "InterArm": 3989,
            "InterArmPercent": 71.0,
            "Total": 7121,
            "TotalPercent": 68.8,
        },
        "Scheduled castes": {
            "ControlArm": 354,
            "ControlArmPercent": 7.5,
            "InterArm": 451,
            "InterArmPercent": 8.0,
            "Total": 805,
            "TotalPercent": 7.8,
        },
        "Other backward classes": {
            "ControlArm": 872,
            "ControlArmPercent": 18.5,
            "InterArm": 949,
            "InterArmPercent": 16.9,
            "Total": 1821,
            "TotalPercent": 17.6,
        },
        "Other": {
            "ControlArm": 366,
            "ControlArmPercent": 7.7,
            "InterArm": 232,
            "InterArmPercent": 4.1,
            "Total": 598,
            "TotalPercent": 5.8,
        },
    },
    "Occupation†": {
        "Unemployed": {
            "ControlArm": 237,
            "ControlArmPercent": 5.0,
            "InterArm": 188,
            "InterArmPercent": 3.3,
            "Total": 425,
            "TotalPercent": 4.1,
        },
        "MGNREGS, labour, sell forest products, and rickshaw driver": {
            "ControlArm": 1005,
            "ControlArmPercent": 21.3,
            "InterArm": 1307,
            "InterArmPercent": 23.3,
            "Total": 2312,
            "TotalPercent": 22.3,
        },
        "Sell milk, vegetables, livestock, and small-scale trade": {
            "ControlArm": 48,
            "ControlArmPercent": 1.0,
            "InterArm": 75,
            "InterArmPercent": 1.3,
            "Total": 123,
            "TotalPercent": 1.2,
        },
        "Making or selling of baskets, and making or selling alcohol or tobacco": {
            "ControlArm": 15,
            "ControlArmPercent": 0.3,
            "InterArm": 19,
            "InterArmPercent": 0.3,
            "Total": 34,
            "TotalPercent": 0.3,
        },
        "Pensions, employment in mines, or contract jobs": {
            "ControlArm": 215,
            "ControlArmPercent": 4.6,
            "InterArm": 132,
            "InterArmPercent": 2.3,
            "Total": 347,
            "TotalPercent": 3.4,
        },
        "Medium and large-scale trade, and income from land": {
            "ControlArm": 8,
            "ControlArmPercent": 0.2,
            "InterArm": 23,
            "InterArmPercent": 0.4,
            "Total": 31,
            "TotalPercent": 0.3,
        },
        "Student": {
            "ControlArm": 1627,
            "ControlArmPercent": 34.4,
            "InterArm": 2005,
            "InterArmPercent": 35.7,
            "Total": 3632,
            "TotalPercent": 35.1,
        },
        "Home maker": {
            "ControlArm": 963,
            "ControlArmPercent": 20.4,
            "InterArm": 1242,
            "InterArmPercent": 22.1,
            "Total": 2205,
            "TotalPercent": 21.3,
        },
        "Not applicable‡": {
            "ControlArm": 606,
            "ControlArmPercent": 12.8,
            "InterArm": 630,
            "InterArmPercent": 11.2,
            "Total": 1236,
            "TotalPercent": 11.9,
        },
    },
    "Public distribution system§": {
        "Yes": {
            "ControlArm": 3968,
            "ControlArmPercent": 84.0,
            "InterArm": 4825,
            "InterArmPercent": 85.8,
            "Total": 8793,
            "TotalPercent": 85.0,
        }
    },
    "Tobacco": {
        "Yes": {
            "ControlArm": 347,
            "ControlArmPercent": 7.3,
            "InterArm": 552,
            "InterArmPercent": 9.8,
            "Total": 899,
            "TotalPercent": 8.7,
        }
    },
    "Alcohol": {
        "Yes": {
            "ControlArm": 707,
            "ControlArmPercent": 15.0,
            "InterArm": 746,
            "InterArmPercent": 13.3,
            "Total": 1453,
            "TotalPercent": 14.0,
        }
    }
}
if __name__ == "__main__":
    import pprint
    pprint.pprint(data)
