project:
  type: website
  output-dir: _site
  title: "TBSim"
  execute-dir: file

website:
  title: "TBSim"
  image: /assets/tbsim-logo.png
  favicon: /assets/favicon.ico

  repo-url: https://github.com/your-org/tbsim
  repo-actions: [issue]
  page-navigation: true
  search:
    type: overlay

  page-footer:
    center: "The docs were built for TBSim v{{< var version >}} ({{< var versiondate >}}).<br>© 2024, TBSim Contributors. All rights reserved."
    right:
      - icon: github
        href: https://github.com/your-org/tbsim
        aria-label: GitHub
      - icon: envelope-at-fill
        href: mailto:info@tbsim.org
      - icon: globe
        href: https://tbsim.org/

  navbar:
    logo: /assets/tbsim-logo.png
    title: false
    collapse-below: lg

    tools:
      - icon: github
        href: https://github.com/your-org/tbsim
      - icon: envelope-at-fill
        href: mailto:info@tbsim.org
      - icon: globe
        href: https://tbsim.org

    left:
      - href: index.qmd
        text: Home
      - href: whatsnew.qmd
        text: What's new
      - href: tutorials.qmd
        text: Tutorials
      - href: user_guide.qmd
        text: User guide
      - href: api/index.qmd
        text: API reference

  sidebar:
    - id: main
      collapse-level: 3
      contents:
        - href: index.qmd
          text: "**Home**"
        - href: whatsnew.qmd
          text: "**What's new**"
        - section: "**Tutorials**"
          contents:
            - href: tutorials.qmd
              text: "**Tutorials**"
            - tutorials/example_tutorial.qmd
            - tutorials/tuberculosis_sim.qmd
            - tutorials/tb_interventions_tutorial.qmd
            - tutorials/run_tbhiv_scens.qmd
            - tutorials/tbhiv_comorbidity.qmd
            - tutorials/dots_implementation_tutorial.qmd
        - section: "**User Guide**"
          contents:
            - href: user_guide.qmd
              text: "**User guide**"
            - user_guide/intro_tbsim.qmd
            - user_guide/basics_model.qmd
            - user_guide/basics_sim.qmd
            - user_guide/basics_parameters.qmd
        - section: "**Modules**"
          contents:
            - user_guide/modules_diseases.qmd
            - user_guide/modules_networks.qmd
            - user_guide/modules_demographics.qmd
            - user_guide/modules_interventions.qmd
            - user_guide/modules_analyzers.qmd
    - id: api
      collapse-level: 2
      contents:
        - href: index.qmd
          text: "**Home**"
        - href: api/index.qmd
          text: "**API reference**"
        - section: "**Core**"
          contents:
            - api/sim.qmd
            - api/tb.qmd
            - api/networks.qmd
            - api/analyzers.qmd
        - section: "**Modules**"
          contents:
            - api/comorbidities.qmd
            - api/interventions.qmd
            - api/utils.qmd
        - section: "**Utilities**"
          contents:
            - api/config.qmd
            - api/wrappers.qmd
            - api/version.qmd

format:
  html:
    theme: 
      light: [cosmo, ./assets/styles-light.scss]
      dark: [cosmo, ./assets/styles-dark.scss]
    css: ./assets/styles.css
    toc: true
    toc-depth: 3
    highlight-style: github

filters:
  - interlinks

quartodoc:
  package: tbsim
  title: API reference
  style: pkgdown
  dir: api
  parser: google
  sections:
    - title: API reference
      desc: Full details on all TBSim classes and functions.
      contents:
        - analyzers
        - comorbidities
        - config
        - interventions
        - networks
        - tb
        - utils
        - version
        - wrappers

jupyter: python3
execute:
  enabled: true
  daemon: true
  cache: false
  freeze: false
  error: false
  echo: true
  warning: true
  kernel: tbsim-docs
  timeout: 300
