#!/usr/bin/env bash
# Render full site
set -euo pipefail # Fail fast if needed

cd "$(dirname "$0")/.." # great-docs runs from the repo root

SECONDS=0

# Do the render!
great-docs build "$@"

echo -e "Done: docs built in ${SECONDS} s"
echo -e "Index: $(pwd)/great-docs/_site/index.html"
