#!/bin/bash

# Start script for Binder
# This script launches Jupyter with the correct settings

echo "Starting Jupyter notebook server..."

# Set up environment variables
export PYTHONPATH="${PYTHONPATH}:/home/jovyan/work"

# Launch Jupyter notebook
jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' 