name: Publish TBsim docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: "gh-pages"
  cancel-in-progress: true

jobs:
  publish:
    name: Quarto
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/cache@v4
        with:
          key: quarto-${{ runner.os }}-${{ hashFiles('**/requirements.txt', '**/pyproject.toml', '**/_quarto.yml') }}
          path: ~/.cache/pip

      - name: Install TBsim and docs dependencies
        run: |
          pip install -e .[dev]
          pip install -r docs/requirements.txt

      - name: Pre-build font cache  # so it doesn't appear in notebook output
        run: python -c "import tbsim"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Quarto interlinks extension
        working-directory: ./docs
        run: quarto add machow/quartodoc --no-prompt

      - name: Render and publish to gh-pages
        working-directory: ./docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          ./publish
