name: TBsim Unit Tests
# Trigger the workflow on push to the main branch
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      
      # Step 1.1: Checkout the running repository (tbsim)
      - name: Checkout tbsim repository
        uses: actions/checkout@v3
      
      # Step 1.2: Install tbsim
      - name: Install tbsim
        run: |
          ls -l
          pip install -e .
          pip freeze      
          
      # Step 2.1: Checkout starsimhub/starsim repository
      - name: Checkout starsimhub/starsim repository
        uses: actions/checkout@v3
        with:
          repository: 'starsimhub/starsim'
          path: 'starsim'
      
      # Step 2.2: Install starsim
      - name: Install starsim
        run: |
          cd starsim
          pip install -e .
          pip freeze
          
      # Step 3: Run unit tests for tbsim
      - name: Run unit tests
        working-directory: ./tests
        run: |
          ls -l
          python -m unittest discover .
