name: Install Dependencies and Run Tests Workflow

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1.1: Checkout starsimhub/starsim repository
      - name: Checkout starsimhub/starsim repository
        uses: actions/checkout@v3
        with:
          repository: 'starsimhub/starsim'
          path: 'starsim'
      
      # Step 1.2: Install starsim
      - name: Install starsim
        run: |
          cd starsim
          pip install -e .
      
      # Step 2.1: Checkout the running repository (tbsim)
      - name: Checkout tbsim repository
        uses: actions/checkout@v3
        with:
          path: 'tbsim'
      
      # Step 2.2: Install tbsim
      - name: Install tbsim
        run: |
          cd tbsim
          pip install -e .

      # Step 3: Run unit tests for tbsim
      - name: Run unit tests
        run: |
          cd tbsim
          python -m unittest discover
